version: '3'
services:
  ng-rolodex:
    image: syamashige/ng-rolodex:${iMAGE_VERSION}
    env_file: .env
    environment:
      NODE_ENV: production
    depends_on:
      - postgres-primary-db
      - redis-session-store
    command: ["node", "app.js"]
    container_name: ng-rolodex-prod
    ports:
      - "${EXPRESS_HOST_PORT}:${EXPRESS_CONTAINER_PORT}"
    networks:
      - rolodex-app-network
  postgres-primary-db:
    image: postgres:10.0-alpine
    env_file: .env
    volumes: 
      - pg-data-volume:/var/lib/postgresql/data
    ports: 
      - '${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}'
    networks:
      - rolodex-app-network
  redis-session-store:
    image: redis:4.0-alpine
    env_file: .env
    volumes:
      - redis-data-volume:/data
    ports:
      - '${REDIS_HOST_PORT}:${REDIS_CONTAINER_PORT}'
    networks:
      - rolodex-app-network

  

volumes: 
  pg-data-volume:
  redis-data-volume:
networks:
  rolodex-app-network: